@startuml EmpresaPanificadora
class Dirección{}
class EmpresaPanificadora{}
class VicepresidenciaEjecutiva{}
class Laboratorio {}
class Mezclas{}
class Manufactura {}
class GestionHumana {}
class SeguridadIndustrial{}
class GerenciaAdministrativa{}
class Mantenimiento {}
class RevisionFiscal {}
class Embalaje {
  +proteccionProducto()
  +manejoTransporte()
  +utilizacionEquipoTransporte()
}

class LineaEmpaque {
  +embalarProducto()
}

class Producto {
  -referencia
  -participacionProduccion
  +getReferencia()
  +getParticipacionProduccion()
}

class Operario {
  -nombre
  +realizarVerificacion()
}

class Canasta {
  -productoEmbalado
  -cantidad
  -calidad
  -fechaEmbalaje
  +verificarCantidad()
  +verificarCalidad()
  +verificarFechaEmbalaje()
}

EmpresaPanificadora "1" *-- "1" Dirección 
Dirección "1" *-- "1" VicepresidenciaEjecutiva
VicepresidenciaEjecutiva "1" *-- "1" Laboratorio
VicepresidenciaEjecutiva "1" *-- "1" Mezclas
VicepresidenciaEjecutiva "1" *-- "1" Manufactura 
VicepresidenciaEjecutiva "1" *-- "1" GerenciaAdministrativa 
VicepresidenciaEjecutiva "1" *-- "1" Mantenimiento
VicepresidenciaEjecutiva "1" *-- "1" RevisionFiscal
VicepresidenciaEjecutiva "1" *-- "1" GestionHumana
VicepresidenciaEjecutiva "1" *-- "1" SeguridadIndustrial
Manufactura "1" *-- "1" Embalaje
Embalaje "1" *-- "1.." LineaEmpaque
LineaEmpaque "1" *-- "1.."  Producto
LineaEmpaque "1" *-- "1.." Operario
Operario "1.." *-- "1" Canasta
@enduml